services:
  db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: insurance_accumulator
    ports:
      - "5432:5432"
volumes:
  db:
    driver: local
